### ISSUE TITLE
Tooltip issues/ideas

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#86]
Tooltip has some issues on Mac and I have some ideas. First and foremost is the usage of the toplevel:
 1. On mac this makes quite a weird illusion and looks pretty bad. I recommend that we use the button idea and that we just position and un-position as it was initially. My picture of the issue is attached. 
 2. I believe that the time for scheduling should be halved to 500 ms instead of a whole second. I also removed the schedule to remove the tooltip after a set time because it seems like it could lead to issues for large amounts of text. 
 3. Using newlines makes it look janky because its not an actual button. Image is attached
 4. Users should be able to specify which side the tooltip goes too and I think it would be good if the tooltip keeps the same theming
 5. Make sure that the tooltip keeps the font of the owner widget

Proposed code:
```python
    @classmethod
    def schedule(cls, widget: str) -> None:
        cls._can_show = True

        message = cls._widgets.get(widget)
        if message is None:
            return

        Tcl.call(None, ".tooltip.label", "configure", "-text", message)
        cls._after_id = Tcl.call(str, "after", 500, cls._show_cmd, widget)


    @classmethod
    def show(cls, widget: str) -> None:
        if not cls._can_show:
            return

        owner_x = Tcl.call(int, "winfo", "rootx", widget)
        owner_width = Tcl.call(int, "winfo", "reqwidth", widget)
        tip_width = Tcl.call(int, "winfo", "reqwidth", ".tooltip")
        tip_x = owner_x + owner_width // 2 - tip_width // 2

        owner_y = Tcl.call(int, "winfo", "rooty", widget)
        tip_height = Tcl.call(int, "winfo", "reqheight", ".tooltip")
        tip_y = owner_y - tip_height - 5

        if tip_y <= Tcl.eval(int, f"winfo rooty [winfo toplevel {widget}]"):
            tip_y = owner_y + Tcl.call(int, "winfo", "reqheight", widget) + 5

        Tcl.call(None, "wm", "geometry", ".tooltip", f"+{tip_x}+{tip_y}")
        Tcl.call(None, "wm", "deiconify", ".tooltip")

```

Images:

 1. <img width="120" alt="Screen Shot 2022-07-03 at 9 24 37 PM" src="https://user-images.githubusercontent.com/95927277/177071304-cdee3447-41ef-49cd-8797-0e52e5153432.png"> 
 2 . <img width="490" alt="Screen Shot 2022-07-03 at 9 38 19 PM" src="https://user-images.githubusercontent.com/95927277/177072386-56fae148-0fbf-426c-a903-4a12b1148bc3.png">

**Comment by rdbende** [comment]
### TODO
- [x] Reduce default tooltip delay
- [x] Intelligently set delay before disappearance
- [ ] Fix newline problem with Aqua theme
- [ ] Make sure it doesn't go off-screen
- [ ] Make sure it looks right with any theme

**Comment by rdbende** [comment]
![image](https://user-images.githubusercontent.com/77941087/199127020-35518b59-c078-4bab-83e8-586e66075d7b.png)
